version: "3.9"
services:
  webapp:
    build: .
    container_name: webapp
    # Descomenta UMA linha de platform dependendo do Mac:
    # platform: linux/arm64   # Apple Silicon (recomendado)
    # platform: linux/amd64   # se precisares emular amd64
    ports:
      - "8080:8080"
    environment:
      - UPLOAD_FOLDER=/app/data
      - FLASK_ENV=production
      - PUID=1000
      - PGID=1000
    # Para j√° usa uma pasta local para dados (trocaremos para NFS depois)
    volumes:
      - dados_nfs:/app/data
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped
volumes:
  dados_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.64.5,nfsvers=4,proto=tcp,rw,noatime"
      device: ":/dados_webapp"